[build]
  command = "pnpm run build"
  publish = "build/client"
  
[build.environment]
  NODE_VERSION = "18.18.0"
  NPM_FLAGS = "--version"

[functions]
  directory = "build/server"

[[redirects]]
  from = "/_data/*"
  to = "/.netlify/functions/_data/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
    [headers.values]
    "Cache-Control" = "public, max-age=0, must-revalidate"
